openapi: 3.0.3
info:
  title: SCS
  description: This document demonstrates the server APIs and how to send/receive data from them.
  version: '1.0'
  contact:
    name: Laith Al-Helwany
    email: laith.helwany@gmail.com
    url: https://www.fb.com/laithhelwany
    x-phone: '00963934189422'
servers:
  - url: https://localhost:1337
    description: For local development
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Client:
      type: object
      properties:
        phoneNumber:
          type: string
          default: 0123456789
        userName:
          type: string
          default: userName
        password:
          type: string
          default: password
      required: 
        - phoneNumber
        - userName
        - password
    createClientResponse:
      type: object
      properties:
        userId:
          type: string
          default: 1
        
security:
  - bearerAuth: []
tags:
  - name: Client
    description: Client Related Endpoints
paths:
  /client:
    post:
      tags:
        - Client
      summary: Create new Client
      description: Add new Client to the database
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createClientResponse'
